force-app/main/default/objects/Object_Mapping__c/Object_Mapping__c.object-meta.xml
<CustomObject>
    <label>Object Mapping</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mapping__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__c/fields/Filter_State_JSON__c.field-meta.xml
<CustomField>
    <fullName>Filter_State_JSON__c</fullName>
    <label>Filter State JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__c/fields/Object_Mapping_Layout__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping_Layout__c</fullName>
    <label>Object Mapping Layout</label>
    <referenceTo>Object_Mapping_Layout__c</referenceTo>
    <relationshipLabel>Object Mappings</relationshipLabel>
    <relationshipName>Object_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__c/fields/Object_Mapping_Template__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping_Template__c</fullName>
    <label>Object Mapping Template</label>
    <referenceTo>Object_Mapping_Template__c</referenceTo>
    <relationshipLabel>Object Mappings</relationshipLabel>
    <relationshipName>Object_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__c/fields/Source_Object_Relationship_JSON__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Relationship_JSON__c</fullName>
    <label>Source Object Relationship JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__c/fields/Target_Object_Relationship_JSON__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Relationship_JSON__c</fullName>
    <label>Target Object Relationship JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Layout__c/Object_Mapping_Layout__c.object-meta.xml
<CustomObject>
    <label>Object Mapping Layout</label>
    <nameField>
        <label>Object Mapping Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Mapping Layouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mapping_Layout__c/fields/Parent_Object_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object_Mapping__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Parent Object Mapping</label>
    <referenceTo>Object_Mapping__c</referenceTo>
    <relationshipLabel>Object Mapping Layouts</relationshipLabel>
    <relationshipName>Parent_Object_Mapping_Layouts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Layout__c/fields/Parent_Source_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Source_Object_Api_Name__c</fullName>
    <formula>Parent_Object_Mapping__r.Object_Mapping_Template__r.Source_Object_Api_Name__c</formula>
    <label>Parent Source Object Api Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Template__c/Object_Mapping_Template__c.object-meta.xml
<CustomObject>
    <label>Object Mapping Template</label>
    <nameField>
        <label>Object Mapping Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Mapping Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mapping_Template__c/fields/Mapping_Data__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Data__c</fullName>
    <label>Mapping Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Template__c/fields/Source_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Api_Name__c</fullName>
    <label>Source Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Template__c/fields/Target_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Api_Name__c</fullName>
    <label>Target Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ObjectMappingLayoutsSelector.cls
public inherited sharing class ObjectMappingLayoutsSelector {

    /**
     * Retrieves an Object_Mapping_Layout__c represented as ObjectMappingLayout object by its Id.
     *
     * @param objectMappingLayoutId The Id of the Object_Mapping_Layout__c to retrieve.
     * @param isFieldMappingsIncluded If true, the field mappings are included in the template instances.
     * @return An ObjectMappingLayout object representing the retrieved Object_Mapping_Layout__c record,
     * along with any associated Object_Mapping__c records if no Object_Mapping_Layout__c record is found, null is returned.
    */
    public ObjectMappingLayout getObjectMappingLayoutWithObjectMappings(Id objectMappingLayoutId,Boolean isFieldMappingsIncluded){
        ObjectUtil.requireNonNull(objectMappingLayoutId, 'objectMappingLayoutId cannot be null ' +
                'to retrieve ObjectMappingLayout for display.');

        String queryString = 'SELECT Id,Name,IsDefault__c,Parent_Object_Mapping__c,' +
                '(SELECT Id,' +
                'External_Id__c,' +
                'Object_Mapping_Template__c,' +
                'Filter_State_JSON__c,' +
                'Target_Object_Relationship_JSON__c,' +
                'Source_Object_Relationship_JSON__c,' +
                'Object_Mapping_Template__r.Id,' +
                'Object_Mapping_Template__r.Source_Object_Api_Name__c,' +
                'Object_Mapping_Template__r.Target_Object_Api_Name__c,' +
                'Object_Mapping_Template__r.Description__c,' +
                'Object_Mapping_Template__r.Name' +
                (isFieldMappingsIncluded ?',Object_Mapping_Template__r.Mapping_Data__c':' ') +
                ' FROM Object_Mappings__r ) FROM Object_Mapping_Layout__c ' +
                'WHERE Id=:objectMappingLayoutId';

        List<Object_Mapping_Layout__c> objectMappingLayouts = Database.query(queryString);

        Object_Mapping_Layout__c objectMappingLayoutSObject = objectMappingLayouts.size()==1?objectMappingLayouts.get(0):null;
        if(objectMappingLayoutSObject==null){
            return null;
        }
        return ObjectMappingLayout.ofSObject(objectMappingLayoutSObject,objectMappingLayoutSObject.Object_Mappings__r);
    }
    /**
    * Returns all Object_Mapping_Layout__c represented as ObjectMappingLayout instances with Id, Name ,IsDefault and
     * Description fields.
    *
    * @return A list of ObjectMappingLayout instances.
    */
    public List<ObjectMappingLayout> getObjectMappingLayouts(){
        if(!Object_Mapping_Layout__c.getSObjectType().getDescribe().isAccessible()){
            throw new SObjectException('Do not have access to Object_Mapping_Layout__c object.');
        }
        List<Object_Mapping_Layout__c> objectMappingLayoutSObjects =
                Database.query('SELECT Id,Name,Description__c,IsDefault__c'+
                        ' FROM Object_Mapping_Layout__c ORDER BY Name');

        return ObjectMappingLayout.ofSObjects(objectMappingLayoutSObjects);
    }
    /**
      * This method returns a list of Object_Mapping_Layout__c represented as ObjectMappingLayout instances
      * with fields Id ,IsDefault, Name and Description.
      * Sharing rules are NOT enforced for this query.
      * Use this for showing available Object Mapping Layouts for a given source object for any users.
      *
      * @param sourceObjectApiName the API name of the parent source object for which to retrieve associated
       * Object Mapping Layout records
      *
      * @return A list of ObjectMappingLayout instances.
    */
    public List<ObjectMappingLayout> getObjectMappingLayoutsByParentSourceObject(String sourceObjectApiName){
        ObjectUtil.requireNonNull(sourceObjectApiName, 'sourceObjectApiName cannot be null to ' +
                'retrieve ObjectMappingLayouts by parent source object.');

        List<Object_Mapping_Layout__c> objectMappingLayoutSObjects =
                ObjectUtil.executeQueryWithoutSharing('SELECT Id,Name,Description__c, IsDefault__c ' +
                        'FROM Object_Mapping_Layout__c ' +
                        'WHERE Parent_Source_Object_Api_Name__c =:sourceObjectApiName ' +
                        'ORDER BY Name',
                        new Map<String,Object>{'sourceObjectApiName'=>sourceObjectApiName});
        return ObjectMappingLayout.ofSObjects(objectMappingLayoutSObjects);
    }
}