force-app/main/default/objects/Object_Mapping__c/Object_Mapping__c.object-meta.xml
<CustomObject>
    <label>Object Mapping</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Object Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Mappings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mapping__c/fields/Object_Mapping_Layout__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping_Layout__c</fullName>
    <label>Object Mapping Layout</label>
    <referenceTo>Object_Mapping_Layout__c</referenceTo>
    <relationshipLabel>Object Mappings</relationshipLabel>
    <relationshipName>Object_Mappings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_Mapping__c/fields/Object_Mapping_Template__c.field-meta.xml
<CustomField>
    <fullName>Object_Mapping_Template__c</fullName>
    <label>Object Mapping Template</label>
    <referenceTo>Object_Mapping_Template__c</referenceTo>
    <relationshipLabel>Object Mappings</relationshipLabel>
    <relationshipName>Object_Mappings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Layout__c/Object_Mapping_Layout__c.object-meta.xml
<CustomObject>
    <label>Object Mapping Layout</label>
    <nameField>
        <label>Object Mapping Layout Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Mapping Layouts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mapping_Template__c/Object_Mapping_Template__c.object-meta.xml
<CustomObject>
    <label>Object Mapping Template</label>
    <nameField>
        <label>Object Mapping Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Mapping Templates</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Mapping_Template__c/fields/Mapping_Data__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Data__c</fullName>
    <label>Mapping Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Template__c/fields/Source_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Source_Object_Api_Name__c</fullName>
    <label>Source Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Mapping_Template__c/fields/Target_Object_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Api_Name__c</fullName>
    <label>Target Object Api Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ObjectMappingTemplateServiceTest.cls
@IsTest
public class ObjectMappingTemplateServiceTest {


    @IsTest
    static void testUpsertObjectMappingTemplate() {
        // Given
        ObjectMappingTemplate objectMappingTemplate = new ObjectMappingTemplate();
        objectMappingTemplate.name = 'Test Template';
        objectMappingTemplate.sourceObjectApiName = 'Contact';
        objectMappingTemplate.targetObjectApiName = 'Account';
        objectMappingTemplate.description = 'Test Description';

        FieldMapping.Field contactPhoneFromField = new FieldMapping.Field('Phone','Business Phone',false,'PHONE',null);
        FieldMapping.Field accountPhoneToField = new FieldMapping.Field('Phone','Account Phone',false,'PHONE',null);
        FieldMapping contactPhoneToAccountPhoneMapping = new FieldMapping('3',contactPhoneFromField,accountPhoneToField);
        objectMappingTemplate.fieldMappings = new List<FieldMapping>{contactPhoneToAccountPhoneMapping};

        ObjectMappingTemplateService objectMappingTemplateService = new ObjectMappingTemplateServiceImpl();

        // When
        Id actualTemplateId = objectMappingTemplateService.upsertObjectMappingTemplate(objectMappingTemplate);

        // Then
        Assert.isNotNull(actualTemplateId);

        Object_Mapping_Template__c mappingTemplateSObject = [SELECT Id, Name, Source_Object_Api_Name__c, Description__c,
                                                            Target_Object_Api_Name__c, Mapping_Data__c
                                                            FROM Object_Mapping_Template__c WHERE Id = :actualTemplateId LIMIT 1];

        Assert.areEqual(objectMappingTemplate.name, mappingTemplateSObject.Name);
        Assert.areEqual(objectMappingTemplate.sourceObjectApiName, mappingTemplateSObject.Source_Object_Api_Name__c);
        Assert.areEqual(objectMappingTemplate.targetObjectApiName, mappingTemplateSObject.Target_Object_Api_Name__c);
        Assert.areEqual(objectMappingTemplate.description, mappingTemplateSObject.Description__c);
        Assert.areEqual(JSON.serialize(objectMappingTemplate.fieldMappings), mappingTemplateSObject.Mapping_Data__c);

    }


    @IsTest
    static void testDeleteObjectMappingTemplateWithNoRelationToAnyObjectMappingLayout() {
        // Given
        Object_Mapping_Template__c objectMappingTemplateSobject =
                ObjectMappingTemplateDataFactory.createObjectMappingTemplate( true);

        ObjectMappingTemplateService objectMappingTemplateService = new ObjectMappingTemplateServiceImpl();

        // When
        Test.startTest();
        objectMappingTemplateService.deleteObjectMappingTemplate(objectMappingTemplateSobject.Id);
        Test.stopTest();

        // Then
        Assert.areEqual(0,[SELECT Id FROM Object_Mapping_Template__c WHERE Id = :objectMappingTemplateSobject.Id LIMIT 1].size());
    }
    @IsTest
    static void testDeleteObjectMappingTemplateWithRelationToObjectMappingLayout() {
        // Given
        Object_Mapping_Template__c objectMappingTemplateSobject =
                ObjectMappingTemplateDataFactory.createObjectMappingTemplate( true);

        Object_Mapping_Layout__c objectMappingLayoutSobject = new Object_Mapping_Layout__c();
        objectMappingLayoutSobject.Name = 'Test Layout';
        insert objectMappingLayoutSobject;

        Object_Mapping__c objectMappingSobject = new Object_Mapping__c();
        objectMappingSobject.Object_Mapping_Template__c = objectMappingTemplateSobject.Id;
        objectMappingSobject.Object_Mapping_Layout__c = objectMappingLayoutSobject.Id;
        insert objectMappingSobject;

        ObjectMappingTemplateService objectMappingTemplateService = new ObjectMappingTemplateServiceImpl();

        String exceptionMessage;
        // When
        Test.startTest();
        try{
            objectMappingTemplateService.deleteObjectMappingTemplate(objectMappingTemplateSobject.Id);
        }catch (Exception e){
            exceptionMessage = e.getMessage();
        }

        Test.stopTest();

        // Then
        Assert.isNotNull(exceptionMessage);
        Assert.areEqual(objectMappingTemplateSobject.Id,[SELECT Id FROM Object_Mapping_Template__c WHERE Id = :objectMappingTemplateSobject.Id LIMIT 1].Id);
    }

}